import Head from "next/head"
import Image from "next/image"

const PortfolioContent = () => {
    return (
      <div>
      <Head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Marincor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container__section'>
        <section className='container__title'>
          <h2 className='title'>
            Portfolio
          </h2>
        </section>
       <section className="container__portfolio-content">
       <ul className="portfolio__list">
            <li className="portfolio__item" style={{ background: `url(https://raw.githubusercontent.com/Marincor/marincor_dev/main/public/assets/imgs/projects/money_control.png)`, backgroundColor: "rgba(55, 54, 59, 0.5)", backgroundBlendMode: "color", backgroundRepeat: "no-repeat", backgroundSize: "cover", backgroundPosition: "center"}}>
                <h3 className="project__name">
                 Money Control
                </h3>
                <p className="project__text">
                Aplicação para controle e gerenciamento de gastos. Foi criada com a ideia de ter uma visão macro sobre os gastos mensais e um comparativo de ganhos e custos em relação ao mês atual e o anterior do ano vigente. 
                </p>
                <ul className="tag__list">
                  <li className="tag__item">
                      <small className="tag__name">
                        html
                      </small>
                  </li>
                  <li className="tag__item">
                      <small className="tag__name">
                        html
                      </small>
                  </li>
                  <li className="tag__item">
                      <small className="tag__name">
                        html
                      </small>
                  </li>
           
                </ul>
            </li>
        </ul>

       </section>
      </main>
    </div>
    )
};

export default PortfolioContent;