import Head from "next/head"
import Image from "next/image"

const PortfolioContent = () => {
    return (
      <div>
      <Head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Marincor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container__section'>
        <section className='container__title'>
          <h2 className='title'>
            Portfolio
          </h2>
        </section>

      </main>
    </div>
    )
};

export default PortfolioContent;