import type { NextPage } from 'next'
import Head from 'next/head'

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Marincor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container__section'>
        <section className='container__title'>
          <h2 className='title'>
            about
          </h2>
        </section>
        <section className='container__content'>
          <p className="content">
            Olá, sou Gabriel Marinho, desenvolvedor front-end. Depois de ter estruturado uma conta digital na parte operacional do negócio, como analista de operações, piloto de reserva e analista QA, resolvi mudar para a área de tecnologia; Adoro aprender e busco dar o melhor de mim em todas as funções, com foco em melhoria de processos e novas implementações. Sou apaixonado por desenvolver e quero transformar uma ideia em algo real!
          </p>
        </section>

      </main>
    </div>
  )
}

export default About;
