import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Marincor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
         <h2  className='author'> 
              <p className='firstname'>Gabriel</p>
              <p className='middlename'>Claudino</p>
              <p className='lastname'>Marinho</p>
         </h2>
          <div className='author-img'>
            
          </div>
       </main>
    </div>
  )
}

export default Home
