import type { NextPage } from 'next'
import Head from 'next/head'
import { FaJs, FaReact } from 'react-icons/fa';
import {SiHtml5, SiCss3, SiTypescript, SiNextdotjs, SiAngular, SiFlutter, SiCypress, SiJest, SiJasmine, SiGoogle } from 'react-icons/si';

const Skills: NextPage = () => {



  return (
    <div>
      <Head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Marincor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container__section'>
        <section className='container__title'>
          <h2 className='title'>
            Skills
          </h2>
        </section>
        <ul className="content__list">
        <li className="content__item">
            <h3 className="title__content">
              HTML
              <SiHtml5 />
            </h3>
          </li>
          <li className="content__item">
            <h3 className="title__content">
              CSS
              <SiCss3 />
            </h3>
          </li>
          <li className="content__item">
            <h3 className="title__content">
              Javascript
              <FaJs />
            </h3>
          </li>
          <li className="content__item">
            <h3 className="title__content">
              Typescript
              <SiTypescript />
            </h3>
          </li>
          <li className="content__item">
            <h3 className="title__content">
              React JS
              <FaReact />
            </h3>
          </li>
          <li className="content__item">
            <h3 className="title__content">
              Next JS
              <SiNextdotjs />
            </h3>
          </li>
          <li className="content__item">
            <h3 className="title__content">
              Angular
              <SiAngular />
            </h3>
          </li>
          <li className="content__item">
            <h3 className="title__content">
              Flutter
              <SiFlutter />
            </h3>
          </li>
          <li className="content__item">
            <h3 className="title__content">
              Cypress
              <SiCypress />
            </h3>
          </li>
          <li className="content__item">
            <h3 className="title__content">
              Jest
              <SiJest />
            </h3>
          </li>
          <li className="content__item">
            <h3 className="title__content">
              Jasmine
              <SiJasmine />
            </h3>
          </li>
          <li className="content__item">
            <h3 className="title__content">
              Goolang
              <SiGoogle />
            </h3>
          </li>
        </ul>
      </main>
    </div>
  )
}

export default Skills;
